import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Container } from "react-bootstrap";
import Navs from "@/components/common/Navs";
import Inicio from "./inicio";


export default function Home() {
  return (
    <>
      <Head>
        <title>Fedra Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Inicio />
      </main>
    </>
  );
}
